### ISSUE TITLE
tip/attributepages.md contains (mostly) data for easy-slide

### ISSUE THREAD

**Issue by loneken79** [swissup/data-migration#1]
Hi,
I've just found this very useful project the `tip/attributepages.md` files seems OK for the `source > document_rules` part but everything else relates to `easy-banner`. It would be really great if you could updates and corrects this file.

It seems that this project is no longer very active and a lot of swissup M1 modules aren't yet referenced either. 
Do you plan to update this repo soon or should we dig in the modules configurations ourself to complete migrations?

Thanks for your hard work guys.

**Comment by tangar76** [comment]
We've updated `tip/attributepages.md`. Everything is pretty straight forward with Attribute Pages. Tables are almost identical in M1 and M2.

@loneken79 if you have any further questions about migration of our modules you can ask here.

PS: all of our clients completed migration to M2. That is why there is not much activity here :upside_down_face:
